version: '3.8'

services:
  browserquest-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browserquest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
